name: CI
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-snapshot'
  # workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: "Execute something"
      run: echo 'ship it'
      shell: pwsh